/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AppointmentRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDatetime' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAppointmentRequests' : IDL.Func(
      [],
      [IDL.Vec(AppointmentRequest)],
      ['query'],
    ),
  'getAppointmentRequest' : IDL.Func(
      [IDL.Nat],
      [AppointmentRequest],
      ['query'],
    ),
  'submitAppointmentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AppointmentRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDatetime' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAppointmentRequests' : IDL.Func(
        [],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'getAppointmentRequest' : IDL.Func(
        [IDL.Nat],
        [AppointmentRequest],
        ['query'],
      ),
    'submitAppointmentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };